import Vue from 'vue'
import Router from 'vue-router'
import InstructionsView from "../views/InstructionsView";
import EvidenceView from "../views/EvidenceView";
import AvatarsView from "../views/AvatarsView";
import IconArrayView from '../views/IconArrayView'
import SocioDemoView from "../views/SocioDemoView";
import LinksView from "../views/LinksView";
import VCMView from "../views/VCMView";
import AboutUs from "../views/AboutUs";
import AutoGenerated from "../views/AutoGenerated";
import Animation from "../views/Animation";
Vue.use(Router);


export default new Router({
    routes: [
        {
            path: '/',
            name: 'Instructions',
            component: InstructionsView
        },
        {
            path: '/Avatars',
            name: 'Avatars',
            component: AvatarsView,
            props: true
        },
        {
            path: '/Evidence',
            name: 'Evidence',
            component: EvidenceView,
            props: true
        },
        {
            path: '/Sociodemo',
            name: 'SocioDemo',
            component: SocioDemoView,
            props: true
        },
        {
            path: '/IconArray',
            name: 'IconArray',
            component: IconArrayView,
            props: true
        },
        {
            path: '/links',
            name: 'Links',
            component: LinksView,
            props: true
        },
        {
            path: '/vcm',
            name: 'Vcm',
            component: VCMView,
            props: true
        },
        {
            path: '/AutoGenerated',
            name: 'AutoGenerated',
            component: AutoGenerated,
            props: true
        },
        {
            path: '/AboutUs',
            name: 'AboutUs',
            component: AboutUs,
            props: true
        },
        {
            path: '/Animation',
            name: 'Animation',
            component: Animation,
            props: true
        }
    ]
})
