<template>
  <v-app id="app">
    <navbar :labels="labels" :route-name="routeName" @langSwitch="changeLabels" />
    <v-main>
      <div class="container" id="ourApp">
        <div class="columns">
          <router-view class="column" :labels="routeLabels"
                       :chosenCharacterFromAvatarsView="chosenCharacterFromAvatarsView"
                       :iconArrayProps="iconArrayProps"
                       @setIconArrayProps="setIconArrayProps"
                       @setCharacterProps="setCharacterProps"
                       @changeRouteName="changeRouteName"
          />
        </div>
      </div>
    </v-main>
  </v-app>
</template>

<script>

import Navbar from "@/components/Navbar";
import textsFr from "@/assets/languages/fr.json";
import textsEn from "@/assets/languages/en.json";
import defaultSettings from '@/assets/json/defaultSettings.json';
export default {
  name: 'App',
  data() {
    return {
      defaultSettings: defaultSettings,
      labels: "",
      routeName: "",
      currentLanguage: "",
      chosenCharacterFromAvatarsView : "",
      iconArrayProps: {
        avatar: "",
        targetList: [],
      },
    }
  },
  computed: {
    routeLabels() {
      switch (this.$route.name) {
        case "Avatars":
          return this.labels.avatar
        case "Vcm":
          return this.labels.vcm
        case "Instructions":
          return this.labels.instructions
        case "Evidence":
          return this.labels.evidence
        case "AutoGenerated":
          return this.labels.autoGenerated
        case "SocioDemo":
          return this.labels.socioDemo
        case "Links":
          return this.labels.links
        default:
          return ""
      }
    }
  },
  components: {Navbar},
  methods: {
    /**
     * ---> Loads the labels of the site
     * @return none
     */
    loadLabels() {
      let defaultLanguage = this.defaultSettings.defaultLanguage;
      if (defaultLanguage === "en") {
        localStorage.setItem("language", "en");
        this.labels = textsEn;
        this.currentLanguage = "en";
      } else if (defaultLanguage === "fr" ) {
        localStorage.setItem("language", "fr");
        this.labels = textsFr;
        this.currentLanguage = "fr";
      }
    },

    /**
     * ---> Change the labels of the site
     * @param language String
     * @return none
     */
    changeLabels(language) {
      this.currentLanguage = language;
      if (this.currentLanguage === "fr") {
        localStorage.setItem("language", "fr");
        this.labels = textsFr;
        this.currentLanguage = "fr";
      } else if (this.currentLanguage === "en") {
        localStorage.setItem("language", "en");
        this.labels = textsEn;
        this.currentLanguage = "en";
      }
    },

    /**
     * ---> Sets the icon array props
     * @param payload Object
     * @return none
     */
    setIconArrayProps(payload){
      this.iconArrayProps = payload.iconArrayProps
    },

    /**
     * ---> Sets the character props
     * @param payload Object
     * @return none
     */
    setCharacterProps(payload){
      this.chosenCharacterFromAvatarsView = payload;
      localStorage.setItem("chosenCharacterFromAvatarsView", JSON.stringify(payload));
    },

    /**
     * ---> Sets the good root name of button when change the views
     * @param routeName String
     * @return none
     */
      changeRouteName(routeName){
        this.routeName = routeName;
    }
  },
  created() {
    this.loadLabels();
  },

  mounted() {
    //this.routeName = "Instructions";
  }
}
</script>

<style scoped>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
}

#ourApp {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin: 10px auto;
  padding: 0;
}
</style>
